version: "3.9"

services:

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - 8090:80
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./:/usr/share/nginx/html
    environment:
      - VIRTUAL_HOST=docs.local

networks:
  default:
    external: true
    name: engineer-mogura-network
